### PR TITLE
React Tutorial

### PR DESCRIPTION
**Pull request by astroboyReloaded**
- Create components: `TodoApp`, `Header`, `TodosLogic`, `InputTodo`, `TodosList`, and `TodoItem`.
- Add `useState()` hook to components. 
- Create handlers.
- Add style.
- Add `Reacr.Router`
- Create `Navbar` Component.

### CODE REVIEW

**Comment by nurbolsultanov** [comment]
Hi @astroboyReloaded 
I'm Nurbol Sultanov, and I am going to review your project! 👋
Great Job on getting closer to the finish of your project, you are almost done!!! 🥇

✅ GitHub Flow is correct.
✅ Professional documentation of the project.
❌  No Linters error
✅ Good commit messages

There are some issues that need to be fixed before you will be able to move forward:

❌ Ensure that you implement linters to your project since it is the project requirement. Make sure that you use step-by-step [example](https://github.com/microverseinc/linters-config/tree/master/react-redux) for that. Linters will help to ensure that your project is more clean, readable, and has fewer bugs.

**Comment by astroboyReloaded** [comment]
Hi, @everinurmind, Thank you for your feedback!
- I am sorry, but I was checking the [project requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/exercises/react_tutorial.md), and it does not say anything about **linters**, I also think it is out of the scope of this tutorial. Can you please confirm that this is necessary?
- I did make changes to the README.md

**Comment by nurbolsultanov** [comment]
## Status: APPROVED ♻️
Hi @astroboyReloaded, Your project is complete! There is nothing else to say other than... it's time to merge it 🚀
Congratulations! 🎉

## Highlights:👍🏽

✅ Descriptive Pull Request
✅ GitHub Flow is correct
✅ Professional documentation of the project
✅ Good commit messages

## Optional suggestions:
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

- [ ] Please ensure that you implement linters to your project since it is the Microverse standard [Instructions](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/exercises/full_partner_review.md).

**Cheers and Happy coding!👏👏👏**

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

**Comment by astroboyReloaded** [comment]
Tank you!

**Pull request merged**
